### ISSUE TITLE
How to export as an svg file?

### ISSUE THREAD

**Issue by rCarto** [riatelab/bertinR#2]

**Comment by llongour** [comment]
First try based on r2d3svg dedicated function (https://github.com/hafen/r2d3svg/blob/master/R/save_d3_svg.R)

```r
#' Export to SVG
#'
#' @param bertin map object
#' @param file file
#' @param delay dealy (in seconds) to wait before saving the SVG
#' 
#' @importFrom chromote ChromoteSession
#' @importFrom htmlwidgets saveWidget
#'
#' @return a svg file
#' @export
#'
#' @examples
#' library(sf)
#' world <- st_read(system.file("gpkg/world.gpkg", package = "bertin"),
#'                  layer = "world", quiet = TRUE)
#' map <- bt_layer(data = world, fill = "#808080") |>
#' bt_bubble(data = world, values = "pop", k = 60, tooltip = "$LIBGEO") |>
#' bt_draw()
#' bt_save_svg(bertin = map, file = paste0(getwd(), '/map.svg'), delay = 0.5)
bt_save_svg <- function(bertin, file, background, delay){
  
  file_url <- function(filename) {
    if (.Platform$OS.type == "windows") {
      paste0("file://", normalizePath(filename, mustWork = TRUE))
    } else {
      enc2utf8(paste0("file://", normalizePath(filename, winslash = "/",
                                               mustWork = TRUE)))
    }
  }
  tmp_html <- tempfile('bt_save_svg', fileext = '.html', tmpdir = getwd())
  session <- ChromoteSession$new()
  on.exit(unlink(tmp_html))
  saveWidget(map, file = tmp_html)
  session$Page$navigate(file_url(tmp_html))
  Sys.sleep(delay)
  eval <- paste0(
    "var el = document.getElementById('htmlwidget_container').firstElementChild;\n",
    "el.shadowRoot === null ? el.innerHTML : el.shadowRoot.innerHTML;"
  )
  svg <- session$Runtime$evaluate(eval)$result$value
  cat(svg, file = file)
  invisible(file)
}
```
Maybe we can extend to other formats with `rsvg` ?

**Comment by rCarto** [comment]
oh, that's a good start! 
This solution would add the not so light `chromote` package in Imports (I'll have a look at the dependency tree). 
The svg file is ok on viewers and inkscape. It's not rendered in my browser though (firefox and chromium), same for you?. 


``` r
library(bertin)
library(sf)
#> Linking to GEOS 3.9.0, GDAL 3.2.2, PROJ 7.2.1; sf_use_s2() is TRUE
world <- st_read(system.file("gpkg/world.gpkg", package = "bertin"),
                 layer = "world", quiet = TRUE)
map <- bt_layer(data = world, fill = "#808080") |>
  bt_draw()
bt_save_svg(bertin = map, file = "test.svg", delay = 0.5)
```

<sup>Created on 2022-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
![image](https://user-images.githubusercontent.com/3041254/195550125-c1f81e1e-669c-45bb-bcd3-799e87fc1def.png)


@neocarto , I don't think that comes from the `bertin` js lib, svg exports from observable (at least) are fine.
Anyway, I've added the function to the repo, if you can have a look to be sure...

**Comment by llongour** [comment]
Same on my side, i begin to try another more lightweight method

**Comment by mthh** [comment]
SVG files usually :
- have an XML declaration before the start of the document, something like 
`<?xml version="1.0" standalone="no" encoding="UTF-8"?>` (should not impact the rendering in the browser).
- have to set up the `xmlns` (and optionally `xmlns:xlink`) namespace(s) on the `svg` node, something like  `<svg viewBox="0 0 1152 750" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">` (if `xmlns` is not set, the browser opens the file as a XML document instead of as an SVG image).

Observable and Magrit are both adding the `xmlns` and `xmlns:xlink` namespace declaration when exporting to svg.

**Comment by rCarto** [comment]
> Observable and Magrit are both adding the `xmlns` and `xmlns:xlink` namespace declaration when exporting to svg.

If these two modest projects are doing so, I'm sure we can do the same :wink: in `bertin`.

**Comment by llongour** [comment]
Ok thank you @mthh  ! I just tested with that: `svg <- gsub('^(.{6})(.*)$', '\\1 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" \\2', session$Runtime$evaluate(eval)$result$value)` and it work. I will revise my regex 😬

**Comment by rCarto** [comment]
I close the issue, feel free to post here if something better come up.
